"use client";
import React, { Suspense, useLayoutEffect, useState } from "react";
import { VerificationLinkParams } from "../../../../types/types";
import Image from "next/image";

import Loading from "../../../../components/loading/Loading";
import InvalidLink from "@/components/verification/InvalidLink";
import ValidLink from "@/components/verification/ValidLink";

// export const metadata = {
//   title: "Verify Email",
//   description: "Generated by create next app",
// };

function Verified({ params }: VerificationLinkParams) {
  const [ userId, token ] = params.slug;
  const [isLinkValid, setIsLinkValid] = useState<boolean>(true);
  const [loading, setLoading] = useState<boolean>(true);

  useLayoutEffect(() => {
    (async () => {
      try {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}verification/verify_email/${userId}/${token}`,
          { cache: "no-store" }
        );

        if (response.status !== 200) {
          setLoading(false);
          setIsLinkValid(false);
        } else {
          setLoading(false);
          setIsLinkValid(true);
        }
      } catch (error) {
        console.error(error);
        // Handle the error here
      }
    })();
  }, []);

  if (loading) {
    return <Loading />;
  }

  return (
    <div className="h-screen w-screen md:px-5 lg:px-10 xl:px-14">
      {isLinkValid ? 
        <ValidLink/>
       : 
        <InvalidLink     />
      }
    </div>
  );
}

export default Verified;  