"use client"
import './globals.css'
import { Ubuntu} from 'next/font/google'
import { CircelEffect } from '@/components/CircelEffect'
const inter = Ubuntu({ subsets: ['latin'],weight:'400' })
export const metadata = {
  title: 'GameSell',
  description: 'Generated by create next app',
}

import React from 'react'
import ReduxProvider from '@/redux/provider'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <title>GameSell</title>
      </head>
      <body className={`${inter.className} bg-[#181818] `}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <ToastContainer />

        <CircelEffect Position='top-[10vh] left-52' />
        <CircelEffect Position='left-[80vw] top-[60vh]' />
      </body>
    </html>
  );
}
